[alias]
xtask = "r -rp xtask --"

[build]
rustflags = [
    "-Wfuture-incompatible",
    "-Wlet-underscore",
    "-Wrust-2018-idioms",
    "-Wunused",
]

[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "target-feature=-bulk-memory,-sign-ext,-mutable-globals",
]
rustdocflags = [
    "-Dwarnings",
    "--default-theme=ayu",
    "-Wrustdoc::private_doc_tests",
    "-Wrustdoc::unescaped_backticks",
]
